config/routes.rb
Rails.application.routes.draw do
  resources :books
  
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords'
  }

  resource :users

  root to: 'homes#top'
  get 'about' => 'homes#about'

end

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
        count: resource.errors.count,
        resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center">©Minerva</p>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to "B(ook)rain", root_path, class:"header-title navbar-brand"%>
    <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <div id="nav-search">
        <%= form_tag books_path, :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "検索", :title => nil %>
          </p>
        <% end %>
      </div>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページ", users_path, class: "btn btn-outline-secondary mx-3 my-1"%>
          </li>
          <li class="nav-item ">
            <%= link_to "メモ一覧", books_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "アバウト", about_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B(ook)rain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "layouts/header"%>
      <main>
        <div class="container">
          <div id="flash">
            <%= render "layouts/flash" %>
          </div>
          <%= yield %>
        </div>
      </main>
      <%= render "layouts/footer"%>
    </div>
  </body>
</html>